development:
  adapter: postgresql
  database: reporter_dev
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  database: reporter_test
  host: localhost
  username: postgres
  password: password

production:
  adapter: postgresql
  database: reporter_prodaction
  host: localhost
  username: postgres
  password: password
