development:
  adapter: postgresql
  database: reporter_dev
  host: localhost
  username: postgres
  password: root

test:
  adapter: postgresql
  database: reporter_test
  host: localhost
  username: postgres
  password: root

production:
  adapter: postgresql
  database: reporter_prodaction
  host: localhost
  username: postgres
  password: root
